name: Create Release on Tag Push

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package zip
        uses: vimtor/action-zip@v1
        with:
          files: excalidraw/ icon.png index.html index.js LICENSE plugin.json preview.png react-dom.development.js react.development.js README.md style.css
          dest: result.zip

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "package.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true